/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollaborateursRouteImport } from './routes/collaborateurs'
import { Route as CongesRouteImport } from './routes/conges'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as SheetsRouteImport } from './routes/sheets'
import { Route as VeilleJuridiqueRouteImport } from './routes/veille-juridique'
import { Route as CollaborateursIdRouteImport } from './routes/collaborateurs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateursRoute = CollaborateursRouteImport.update({
  id: '/collaborateurs',
  path: '/collaborateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CongesRoute = CongesRouteImport.update({
  id: '/conges',
  path: '/conges',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetsRoute = SheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const VeilleJuridiqueRoute = VeilleJuridiqueRouteImport.update({
  id: '/veille-juridique',
  path: '/veille-juridique',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateursIdRoute = CollaborateursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollaborateursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/collaborateurs': typeof CollaborateursRouteWithChildren
  '/conges': typeof CongesRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recrutement': typeof RecrutementRoute
  '/sheets': typeof SheetsRoute
  '/veille-juridique': typeof VeilleJuridiqueRoute
  '/collaborateurs/$id': typeof CollaborateursIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/collaborateurs': typeof CollaborateursRouteWithChildren
  '/conges': typeof CongesRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recrutement': typeof RecrutementRoute
  '/sheets': typeof SheetsRoute
  '/veille-juridique': typeof VeilleJuridiqueRoute
  '/collaborateurs/$id': typeof CollaborateursIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/collaborateurs': typeof CollaborateursRouteWithChildren
  '/conges': typeof CongesRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/recrutement': typeof RecrutementRoute
  '/sheets': typeof SheetsRoute
  '/veille-juridique': typeof VeilleJuridiqueRoute
  '/collaborateurs/$id': typeof CollaborateursIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/collaborateurs'
    | '/conges'
    | '/documents'
    | '/integrations'
    | '/parametres'
    | '/rapports'
    | '/recrutement'
    | '/sheets'
    | '/veille-juridique'
    | '/collaborateurs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/collaborateurs'
    | '/conges'
    | '/documents'
    | '/integrations'
    | '/parametres'
    | '/rapports'
    | '/recrutement'
    | '/sheets'
    | '/veille-juridique'
    | '/collaborateurs/$id'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/audit'
    | '/auth'
    | '/collaborateurs'
    | '/conges'
    | '/documents'
    | '/integrations'
    | '/parametres'
    | '/rapports'
    | '/recrutement'
    | '/sheets'
    | '/veille-juridique'
    | '/collaborateurs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CollaborateursRoute: typeof CollaborateursRouteWithChildren
  CongesRoute: typeof CongesRoute
  DocumentsRoute: typeof DocumentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ParametresRoute: typeof ParametresRoute
  RapportsRoute: typeof RapportsRoute
  RecrutementRoute: typeof RecrutementRoute
  SheetsRoute: typeof SheetsRoute
  VeilleJuridiqueRoute: typeof VeilleJuridiqueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborateurs': {
      id: '/collaborateurs'
      path: '/collaborateurs'
      fullPath: '/collaborateurs'
      preLoaderRoute: typeof CollaborateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conges': {
      id: '/conges'
      path: '/conges'
      fullPath: '/conges'
      preLoaderRoute: typeof CongesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheets': {
      id: '/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof SheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veille-juridique': {
      id: '/veille-juridique'
      path: '/veille-juridique'
      fullPath: '/veille-juridique'
      preLoaderRoute: typeof VeilleJuridiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborateurs/$id': {
      id: '/collaborateurs/$id'
      path: '/$id'
      fullPath: '/collaborateurs/$id'
      preLoaderRoute: typeof CollaborateursIdRouteImport
      parentRoute: typeof CollaborateursRoute
    }
  }
}

interface CollaborateursRouteChildren {
  CollaborateursIdRoute: typeof CollaborateursIdRoute
}

const CollaborateursRouteChildren: CollaborateursRouteChildren = {
  CollaborateursIdRoute: CollaborateursIdRoute,
}

const CollaborateursRouteWithChildren = CollaborateursRoute._addFileChildren(
  CollaborateursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CollaborateursRoute: CollaborateursRouteWithChildren,
  CongesRoute: CongesRoute,
  DocumentsRoute: DocumentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  ParametresRoute: ParametresRoute,
  RapportsRoute: RapportsRoute,
  RecrutementRoute: RecrutementRoute,
  SheetsRoute: SheetsRoute,
  VeilleJuridiqueRoute: VeilleJuridiqueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
